insert into artist (name,genre) values ("Bad Bunny", "Reggaeton");
insert into artist (name,genre) values ("Taylor Swift","Pop");
insert into artist (name,genre) values ("Drake","Rap");
insert into artist (name,genre) values ("Harry Styles","Pop");
insert into artist (name,genre) values ("Doja Cat","Hip-Hop");
insert into artist (name,genre) values ("Ed Sheeran","Pop");
insert into artist (name,genre) values ("Metallica","Rock")
insert into song (song_name,id) value ("Titi Me Pregunto",1 );
insert into song (song_name,id) value ("Gato de Noche",1 );
insert into song (song_name,id) value ("Anti-Hero",2 );
insert into song (song_name,id) value ("As It Was",4 );
insert into song (song_name,id) value ("Me Porto Bonito",1 );
insert into song (song_name,id) value ("Moscow Mule",1 );
insert into song (song_name,id) value ("Say So",5 );
insert into song (song_name,id) value ("Talk Dirty",5 );
insert into song (song_name,id) value ("Shape of You",6 );
insert into song (song_name,id) value ("Perfect",6 );
insert into song (song_name,id) value ("Indestructible",7);
insert into song (song_name,id) value ("The Sound of Silence",7);
insert into song (song_name,id) value ("Down with the Sickness",7 );
insert into song (song_name,id) value ("Borderline",8 );
insert into song (song_name,id) value ("Battery",8 );
insert into song (song_name,id) value ("Confusion",8 );
